project_name: saba
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: saba
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: windows
        goarch: arm64
universal_binaries:
  - replace: false
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}_v
      {{ .Arm }}
release:
  prerelease: auto
brews:
  - name: saba
    repository: # HomeBrew Tapをリリースするリポジトリ
      owner: asweed888
      name: homebrew-saba
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    # ここは決め打ちで良い
    folder: Formula
    url_template: "https://github.com/asweed888/saba/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author: # homebrew-tapにcommitするときに使うGitHubアカウント
      name: inadati
      email: dr.inadati@gmail.com
    homepage: "https://github.com/asweed888/saba"
    description: "Declarative development framework saba"     # 適当なdescription
    test: | # リリースビルド後の動作確認用のコマンド。--versionやhelpなどを指定すればよいだろう
      system "#{bin}/saba help"
    install: |  # Goならばバイナリ名でOK
      bin.install "saba"
