[package]
name = "saba"
version = "1.2.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "saba"
path = "src/main.rs"

[dependencies]
clap = "4.4.6"
anyhow = "1.0.75"
di = { path = "./di" }