[package]
name = "saba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
yaml-rust = "0.4.5"
askama = "0.12.1"
lazy_static = "1.4.0"
getset = "0.1.2"
anyhow = "1.0.75"
